import Head from "next/head";
import HomePage from "../core/Templates/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>MM Stock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/LogoMMdevFavicon.jpeg" />
      </Head>
      <main>
        <div>
          <HomePage />
        </div>
      </main>
    </>
  );
}
